### ISSUE TITLE
Use of derived works in the Metadata Extractor project

### ISSUE THREAD

**Issue by drewnoakes** [dvyukov/go-fuzz-corpus#11]
Hi,

Recently we received this issue https://github.com/drewnoakes/metadata-extractor/issues/561 in which @ZanderHuang and @Han0nly submitted several images that trigger exceptions in the Java metadata-extractor library. They explained that those images were derived from images in this repo, with additional fuzzing.

In that library's project we maintain a [corpus of media files used for regression testing](https://github.com/drewnoakes/metadata-extractor-images), which is an amazing asset for us. We try to add images there that trigger undesired behaviour before adding fixes. This helps us maintain quality over time, and parity between the Java and .NET implementations.

Of course adding other people's work to that repository must be done carefully, and so I want to ask whether we are permitted to use these derived works in our own Apache-2.0-licensed library.

Thank you.

**Comment by josharian** [comment]
I am not a lawyer, but my (limited) understanding of the Apache-2.0 license (which this repo also uses) should allow for modification and distribution, so you should be OK. I also strongly suspect that on a personal level, everyone involved in this repo will be cheering you on. :)

**Comment by drewnoakes** [comment]
Thank you for your perspective. I'm also not a lawyer, but the use of Apache-2.0 suggests this kind of use is allowed. I'll ensure any resources added give proper attribution.
